name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Ensure the directory exists
            mkdir -p /home/ubuntu/cicd2
            cd /home/ubuntu/cicd2 || exit 1

            # Check if it's a Git repository
            if [ ! -d ".git" ]; then
              echo "Repository not found! Cloning..."
              git clone git@github.com:yourusername/your-repo.git .
            else
              echo "Repository found! Pulling latest changes..."
              git pull origin main
            fi

            # Install dependencies
            if [ -f package.json ]; then
              npm install
            else
              echo "Error: package.json not found!"
              exit 1
            fi

            # Restart the application using PM2
            pm2 restart all || pm2 start npm --name "cicd2" -- run start
